images: configs/3414.xyz
potential_params:
  potential: repel
path_params: 
  name: mlp
  n_embed: 1
  depth: 2
  activation: gelu
integrator_params: 
  method: dopri5
  rtol: 1.0e-5
  atol: 1.0e-5
  computation: parallel
  sample_type: uniform
  path_loss_name: integral
  path_ode_names: geodesic
optimizer_params:
  optimizer:
    name: adam
    lr: 1.0e-3
  lr_scheduler:
    name: cosine
    T_max: 1000
num_optimizer_iterations: 3
num_record_points: 101
# output_dir: output
