initialization_params:
  images: configs/xyz/hard.xyz
  path_params: 
    name: mlp
    n_embed: 1
    depth: 2
    activation: gelu
  num_record_points: 101
  output_dir: output
  seed: 0
optimization_params:  
  - potential_params:
      potential: repel
    integrator_params: 
      path_ode_names: geodesic
    optimizer_params:
      find_ts: False
      optimizer:
        name: adam
        lr: 1.0e-1
      lr_scheduler:
        name: reducelronplateau
        factor: 0.5
        min_lr: 1.0e-6
    num_optimizer_iterations: 300
  - potential_params:
      potential: morse
    integrator_params: 
      path_ode_names:
        - projected_variational_reaction_energy
        - geodesic
      path_ode_scales:
        - 1.0
        - 0.05
      rtol: 1.0e-5
      atol: 1.0e-6
    optimizer_params:
      optimizer:
        name: adam
        lr: 1.0e-1
    num_optimizer_iterations: 500