initialization_params:
  images: configs/xyz/hard.xyz
  path_params: 
    name: mlp
    n_embed: 1
    depth: 2
    activation: gelu
  num_record_points: 101
  output_dir: output
  seed: 2025
optimization_params:  
  - potential_params:
      potential: morse
    integrator_params: 
      path_ode_names:
        - projected_variational_reaction_energy
        - variable_reaction_energy
      method : dopri5
      rtol: 1.0e-5
      atol: 1.0e-6
    optimizer_params:
      optimizer:
        name: adam
        lr: 1.0e-3
      path_ode_schedulers:
        projected_variational_reaction_energy:
            value: 1.0
            name: linear
            start_value: 1.0
            end_value: 0.0
            last_step: 125
        variable_reaction_energy:
            value: 1.0
            name: linear
            start_value: 0.0
            end_value: 1.0
            last_step: 125
    num_optimizer_iterations: 150