init_params:
  images: configs/rxn0003.xyz
  path_params: 
    name: mlp
    n_embed: 1
    depth: 2
    activation: gelu
  num_record_points: 101
  # output_dir: output
  device: cuda
  seed: 0
opt_params:  
  - potential_params:
      name: repel
    integrator_params: 
      path_ode_names: geodesic
    optimizer_params:
      optimizer:
        name: adam
        lr: 1.0e-1
    num_optimizer_iterations: 1000
  - potential_params:
      name: uma
      model_name: uma-s-1
      task_name: omol
    integrator_params: 
      path_ode_names: projected_variable_reaction_energy
      rtol: 1.0e-5
      atol: 1.0e-7
    optimizer_params:
      optimizer:
        name: adam
        lr: 1.0e-3
    num_optimizer_iterations: 1000
