images: [[1.133, -1.486], [-1.166, 1.477]]

potential_params:
    name: wolfe_schlegel

path_params:
    name: mlp
    n_embed : 8
    depth : 4

integrator_params:
    method : dopri5
    rtol : 1.0e-5
    atol : 1.0e-5
    computation : parallel
    sample_type : uniform
    path_loss_name : growing_string
    path_loss_params:
        weight_type: inv_gauss
    path_ode_names: ['projected_variable_reaction_energy', 'variable_reaction_energy']
    path_ode_scales: [1.0, 0.1]
    


optimizer_params:
    optimizer:
        name: adam
        lr : 1.0e-3 
    path_loss_schedulers:
        weight:
            value: 1.0
            name: cosine
            start_value: 1000.0
            end_value: 0.0
            last_step: 99
        variance:
            value: 1.0
            name: cosine
            start_value: 1.5
            end_value: 0.0
            last_step: 99
    path_ode_schedulers:
        projected_variable_reaction_energy:
            value: 1.0
            name: cosine
            start_value: 1.0
            end_value: 0.0
            last_step: 99
        variable_reaction_energy:
            value: 1.0
            name: cosine
            start_value: 0.0
            end_value: 1.0
            last_step: 99
    TS_region_loss_names: ['E_mean']
    TS_region_loss_scales: [1.0]
    TS_time_loss_names: ['F_mag']
    TS_time_loss_scales: [1.0]
    TS_time_loss_scheduler:
        E_mean:
            value: 1.0
            name: cosine
            start_value: 1.0
            end_value: 0.0
            last_step: 99
    TS_region_loss_scheduler:
        F_mag:
            value: 1.0
            name: cosine
            start_value: 1.0
            end_value: 0.0
            last_step: 99

  

device: cpu

num_optimizer_iterations: 100

output_dir: output