init_params:
  images: [[1.133, -1.486], [-1.166, 1.477]]
  path_params:
    name: mlp
    n_embed : 8
    depth : 4
    activation: gelu
opt_params:
  - potential_params:
      name: wolfe_schlegel
    integrator_params: 
      path_ode_names: projected_variational_reaction_energy
      rtol: 1.0e-5
      atol: 1.0e-7
    optimizer_params:
      optimizer:
        name: adam
        lr: 1.0e-3
    num_optimizer_iterations: 1000